### ISSUE TITLE
New label templates cause error in cut number

### ISSUE THREAD

**Issue by DSCaskey** [valentina-project/vpo2#758]
When loading a pattern created with previous versions, the new label format using the templates causes all the "cut numbers" in the labels to default to one. 

![labels](https://user-images.githubusercontent.com/31944718/30529569-4645c368-9c04-11e7-8a7d-69d3ee427848.JPG)

**Comment by ZoncaD** [comment]
I think you may be using Dismine's Valentina, not the yet-to-be-named independent fork hosted on this repository.  This issue tracker is specifically for versions of the software built from code in this repository.  It's all very confusing during this transitional phase, so this is absolutely no fault of your own.

Dismine's repository & issue tracker are hosted over on Bitbucket (https://bitbucket.org/dismine/valentina).  It looks like he's already copied this issue into his tracker ([#754](https://bitbucket.org/dismine/valentina/issues/754)) and addressed it since you first posted this, too.

**Comment by DSCaskey** [comment]
Nope... the images I posted were from a build from the Git code here. I have noticed Dismine fixed it, but it doesn't resolve the issue here.

**Comment by ZoncaD** [comment]
You are correct!  Sorry!

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#142
