### ISSUE TITLE
Issue: Character encoding needs improvement

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#764]
The `test.val` file found [here](https://forum.valentina-project.org/t/wavy-curves-and-inconsistent-measurements/1988) contains point labels which have non-alphanumeric characters.  (One label set is prefixed with '`Ã„`'.)  Formulas using these characters cannot be used in a formula without giving an error.  May I suggest using a masked input for certain fields?    Back when I was coding, I just created strings of legal characters, then looked up each character that was typed in to see if it was found in the appropriate string.  If it was, it was added to the input string and the string redisplayed.  If not, nothing happened except a reminder popup to only use legal characters, which was associated with that particular string.  It sure saved me a lot of hassles over the years.

![error001](https://user-images.githubusercontent.com/13209333/31369020-524d41a2-ad36-11e7-87db-e8f93153ca24.png)

**Comment by DeadlyDad** [comment]
Upon further research, it looks like a Unicode issue.  When I look at [test.val](https://forum.valentina-project.org/uploads/default/original/2X/b/b5b6ae9df9819731eac5308ab3e4b35dad6597af.val) in both Chrome and Notepad++, directly from the link above, one line with the problematic label reads 

```
<point angle="270" basePoint="23" id="24" length="#hoehe_schoner" lineColor="black" mx="0.716259" my="0.211495" name="Ã„2" type="endLine" typeLine="hair"/>
```

(Those aren't commas, as I found out, but a single character called a 'Double Low-9 Quotation Mark', whatever that is.)

Interestingly enough, when I look at the same file using the TYPE command (which uses ASCII, not Unicode) at a DOS prompt to get the raw text, that line now reads

```
<point angle="270" basePoint="23" id="24" length="#hoehe_schoner" lineColor="black" mx="0.716259" my="0.211495" name="├ä2" type="endLine" typeLine="hair"/>
```

**Comment by DSCaskey** [comment]
So what's causing  Ä to switch to Â,, ? And is it an issue for LibreFashion?

**Comment by slspencer** [comment]
I vote for masked input, it's the only practical solution.
But would we need different input string masks for each character set?

**Comment by DeadlyDad** [comment]
1. I haven't got the foggiest clue what caused `Ä` to switch to `Â,,`, but it did, and that is a problem.
2. I can't speak to using non-Latin alphanumeric characters, as I have never had a reason to delve into it.  [This XML file](http://www.unicode.org/repos/cldr/trunk/common/supplemental/numberingSystems.xml) might or might not help.  It was just something I came across while trying have something helpful to say. :grin:
3. I think that we should continue to use strictly ASCII `A1`/`AA1` nomenclature for labels, using the DEC Alphabet (no **I**, **O**, **Q**, **S**, or **Z** to avoid confusion with numbers): `ABCDEFGHJKLMNPRTUVWXY`

**Comment by slspencer** [comment]
>no **I**, **O**, **Q**, **S**, or **Z**
It's not really appropriate to expect this from our users. All characters in alphabet should be allowed.

**Comment by DSCaskey** [comment]
>I haven't got the foggiest clue what caused Ä to switch to Â,,, but it did, and that is a problem.

 Could you please provide proof why this is a problem for LibreFashion, and not just your computer settings... otherwise we're just chasing squirrels. 
 
>> no I, O, Q, S, or Z
>It's not really appropriate to expect this from our users. All characters in alphabet should be allowed.

I strongly agree... Not only do I not have a problem distinguishing between these chars and numbers, It would break many existing patterns. I happen to use a naming scheme like Front using points F1... Fn, Back B1...Bn, Collar C1...Cn, and Sleeve S1... Sn.

**Comment by slspencer** [comment]
After we switch to UTF-16, we should test if pattern labels using complex characters appear differently in the GUI of a person whose language selection uses a more simple character set.

In any case, switching to UTF-16 is appropriate given the wide range of languages that have been started for our software.

**Comment by DeadlyDad** [comment]
> Could you please provide proof why this is a problem for LibreFashion, and not just your computer settings... otherwise we're just chasing squirrels.

The reason that it is an issue is that it came up.  Period.  (If even *one* system runs into an issue, it needs to be looked into.)  I am running a bog-standard Windows 10 install with no funny language packs installed, just like most users (I would imagine.)  I just opened up the same file in both Chrome and IE on my Windows 10 laptop, and had the same problem.  That is two separate computers with the same issue, and I'll be willing to bet that there are plenty more users that just haven't yet tried opening up that file.  Please ask them to.

>> no I, O, Q, S, or Z

> It's not appropriate to expect this from our users. All characters in any language's alphabet should be allowed.

Fair enough.

> Back to the basics of this issue, our pattern files have as their first line:
`<?xml version="1.0" encoding="UTF-8"? >`
According to this article, http://kunststube.net/encoding/, we should be using UTF-16.

FWIW, Windows apps [use UTF-16 internally](http://tinyurl.com/ycnx33gm).

**Comment by slspencer** [comment]
It's possible that a complex character set may be read incorrectly because it was stored incorrectly as UTF-8. The strange nature of the original labels indicates that a complex character set may be involved in this problem. So, first phase of solving this problem is to convert to UTF-16 for storing and reading from pattern & measurement files.

**Comment by MrDoo71** [comment]
UTF-8 should be fine and is pretty much the de-facto standard for XML in my experience.  If there are character issues then it is not because of a failing of UTF-8, but perhaps reading/writing claiming to be UTF-8 when you're not doing so.

**Comment by slspencer** [comment]
By 'normal', you mean 'western european'?

**Comment by MrDoo71** [comment]
I'd just like to clarify *normal* in my post above.   For the purpose of identifying points so that they can be referred to by other points, and to fit in with the automatic A1, A2 etc. then a restriction to upper case English letters and numbers would not seem unreasonable to me (initial letter followed by zero or more additional letters and numbers).  We should definitely prevent any character that has meaning in our formulas. 

As a nice feature it would be good to be able to provide an optional description for a point. So, I might describe A4 as "waist centre front".   Such text would not be referred to in formula etc, and would be ideal for multi-language support.  So, knowing that "waist centre front" was entered in English, a Russian user might automatically see "фронт талия", text that could be improved no doubt by someone who spoke Russian.

**Comment by slspencer** [comment]
ok, then what's needed is an input mask on the point label fields to prevent underscores and other characters that are meaningful in qmuparser formulas. All other objects are built using point labels (eg Spl_A4_A19, Line_B0_B1)

**Comment by slspencer** [comment]
This chart might be helpful in discussing the problem: http://www.i18nqa.com/debug/utf8-debug.html
**Ä**, when read as a single-byte character, is read as **Ã„** which caused the problem with qmuparser.
I doubt that our user was using **Ã„** in their formulas, they were using a multibyte UTF-8 character, **Ä**.

**Comment by DSCaskey** [comment]
First off... I don't think there is any problem with the use of UTF-8 as the OP believes. I think it's a matter that his machine(s) are not localized correctly? Like MrDoo stated UTF-8 is the standard for XML use and there is really no need to switch to UTF-16. You're going spend a  lot of refactoring just to double the XML file sizes.  In reality UTF-16 and UTF-8, are both capable of encoding all 1,112,064 valid code points in Unicode. For the most part, the only benefit to UTF-16 is when you get into exotic characters such as some long forgotten Tibetan, hieroglyphics or some silly language like Klingon -  where it won't take 4 bytes to encode like it would with UTF-8... the fact is UTF-8 and UTF-16 both encode all Unicode - it's just a matter how many bytes they each use. 

> I doubt that our user was using Ã„ in their formulas, they were using the multibyte UTF-8 character, Ä

Correct... and neither they or I had a problem. 

> ok, then what's needed is an input mask on the point label fields to prevent underscores and other characters that are meaningful in qmuparser formulas. All other objects are built using point labels (eg Spl_A4_A19, Line_B0_B1). But this isn't sufficient...

Don't need a mask at all. For each language you can set in the prefs there is a string of the characters used... The one for German is as follows: 

    switch (list.indexOf(qApp->ValentinaSettings()->GetLabelLanguage()))
    {
        case 0: // de
        {
            const QString al = QStringLiteral("A,Ä,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Ö,P,Q,R,S,ß,T,U,Ü,V,W,X,Y,Z");
            alphabet = al.split(",");
            break;
        }

As you can see A is followed by ,Ä... if the Umlat chars ARE a problem just remove them from the string, but what you will find is you will have the same string as the ENGLISH one. 

Again, I don't believe the UTF-8 is an issue, but in delving into the code I found it interesting that one could change the order of label chars used for the next new piece. For ex I now tend to draw the front of a pattern using F_,then  the back using B_, the sleeves using S_, the collar C_ etc.... and I found having to delete "A1" all the time a PITA. I could change the string to F, B, S, C, etc.... and I'd save a lot of time creating a pattern not having to delete the A1, or B1, etc. Ideally I would make the string a pref that could override the default. 

For more info on UTF-8 vs UTF-16:
http://utf8everywhere.org/
https://en.wikipedia.org/wiki/Unicode
https://en.wikipedia.org/wiki/UTF-8
https://en.wikipedia.org/wiki/UTF-16
http://www.unicode.org/

**Comment by slspencer** [comment]
The problem occurs when a user inputs non-western-european characters into formulas. The user then shares the pattern file with persons whose computers are not set to use those complex characters. The new user tries to open the file but it has now become unreadable because the complex characters have been translated into multiple character strings by the new user's computer.

**Comment by MrDoo71** [comment]
DSCaskey's suggested fix would prevent these characters from being used automatically, so that sounds sensible.

If the decision is that point names should be very limited [a-zA-Z][a-zA-Z0-9]* then a mask on the input control as slspencer suggests would prevent the user from entering these electively.  

The mask also denies _ which is a good thing.  If we decide not to limit the point names as above we should still do the mask.  Note that there already seems to be some kind of mask in play as + - / * are currently converted to _.  We'd need to prevent this too. :-)

Neither change breaks existing files.  Should we just therefore plan to do both?

Regarding "whose computers are not set to use those complex characters".  AFAIK the behaviour shouldn't depend on the locale of the system.  Reading UTF-8 bytes into characters should (must) end up with unicode characters.  The decoding of UTF-8 bytes to unicode characters should not (AFAIK) be influenced in any way by the environment.   If it is dependent on the environment then the code must be using a default decoding for locale rather than specifying UTF-8 which should be pretty easy to check (I'd offer but my C++ is dire).

**Comment by slspencer** [comment]
Both would be appropriate.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#146
