### ISSUE TITLE
New feature: Import measurements from spreadsheet

### ISSUE THREAD

**Issue by slspencer** [valentina-project/vpo2#770]
Add an import function to read in a spreadsheet .csv comma-delimited format.
The Group/Number should be used as the unique key, as the variable name changes per language.
The language should be in the top header.

**Comment by DeadlyDad** [comment]
Another additional option would be to create an export macro within spreadsheet apps.  That wouldn't be too difficult.

**Comment by DSCaskey** [comment]
Seems to me the first obvious issue with importing a spreadsheet with multiple measurements is it does't make sense until there is a functioning multi "made to measure" measurement scheme. 

Otherwise what we're really talking about is the ability to batch process a spreadsheet to produce multiple vit files... not importing. 

>Another additional option would be to create an export macro within spreadsheet apps

That would be one way to do it. Same issue though... it needs to produce multiple vit files.

**Comment by slspencer** [comment]
suggestions are good - but put them on the forum first.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#149
